<?php

namespace Database\Seeders;

use App\Models\HostelRoom;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class HostelRoomSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        HostelRoom::create([
            'id' => 1,
            'hostel_id' => 2,
            'name' => 'Deluxe Kingsss',
            'description' => null,
            'price' => null,
            'sellingprice' => null,
            'bed_type' => null,
            'max_guest' => '3',
            'roomsize' => 11,
            'maxextrabed' => 3,
            'extrabedprice' => 0,
            'totalroom' => 3,
            'roomtype' => null,
            'furnish' => null,
            'is_active' => 1,
            'deleted_at' => null,
            'created_at' => '2023-10-11 07:28:02',
            'updated_at' => '2024-02-11 02:31:02',
            'rentprice_monthly' => 230000,
            'sellingrentprice_monthly' => 264500,
            'rentprice_yearly' => 10000000,
            'sellingrentprice_yearly' => 11500000,
            'totalbathroom' => 5,
            'extrabed_sellingprice' => 0,
        ]);
        HostelRoom::create([
            'id' => 2,
            'hostel_id' => 3,
            'name' => 'Deluxe Twin',
            'description' => null,
            'price' => null,
            'sellingprice' => null,
            'bed_type' => null,
            'max_guest' => '2',
            'roomsize' => 11,
            'maxextrabed' => 3,
            'extrabedprice' => 0,
            'totalroom' => 11,
            'roomtype' => null,
            'furnish' => null,
            'is_active' => 1,
            'deleted_at' => null,
            'created_at' => '2023-10-12 18:31:43',
            'updated_at' => '2023-10-12 18:31:43',
            'rentprice_monthly' => 2000000,
            'sellingrentprice_monthly' => 2300000,
            'rentprice_yearly' => 14000000,
            'sellingrentprice_yearly' => 16100000,
            'totalbathroom' => 4,
            'extrabed_sellingprice' => 0,
        ]);
        HostelRoom::create([
            'id' => 3,
            'hostel_id' => 3,
            'name' => 'Deluxe Double',
            'description' => null,
            'price' => null,
            'sellingprice' => null,
            'bed_type' => null,
            'max_guest' => '2',
            'roomsize' => 11,
            'maxextrabed' => 3,
            'extrabedprice' => 0,
            'totalroom' => 5,
            'roomtype' => null,
            'furnish' => null,
            'is_active' => 1,
            'deleted_at' => null,
            'created_at' => '2023-10-12 18:34:17',
            'updated_at' => '2023-10-12 18:34:17',
            'rentprice_monthly' => 2000000,
            'sellingrentprice_monthly' => 2300000,
            'rentprice_yearly' => 15000000,
            'sellingrentprice_yearly' => 17250000,
            'totalbathroom' => 5,
            'extrabed_sellingprice' => 0,
        ]);
        HostelRoom::create([
            'id' => 4,
            'hostel_id' => 3,
            'name' => 'Standard Double',
            'description' => null,
            'price' => null,
            'sellingprice' => null,
            'bed_type' => null,
            'max_guest' => '2',
            'roomsize' => 11,
            'maxextrabed' => 3,
            'extrabedprice' => 0,
            'totalroom' => 15,
            'roomtype' => null,
            'furnish' => null,
            'is_active' => 1,
            'deleted_at' => null,
            'created_at' => '2023-10-12 18:35:32',
            'updated_at' => '2023-10-12 18:35:32',
            'rentprice_monthly' => 2500000,
            'sellingrentprice_monthly' => 2875000,
            'rentprice_yearly' => 14000000,
            'sellingrentprice_yearly' => 16100000,
            'totalbathroom' => 5,
            'extrabed_sellingprice' => 0,
        ]);
        HostelRoom::create([
            'id' => 5,
            'hostel_id' => 4,
            'name' => 'Superior',
            'description' => null,
            'price' => null,
            'sellingprice' => null,
            'bed_type' => null,
            'max_guest' => '2',
            'roomsize' => 11,
            'maxextrabed' => 3,
            'extrabedprice' => 0,
            'totalroom' => 10,
            'roomtype' => null,
            'furnish' => null,
            'is_active' => 1,
            'deleted_at' => null,
            'created_at' => '2023-10-12 18:39:00',
            'updated_at' => '2023-10-12 18:39:00',
            'rentprice_monthly' => 1500000,
            'sellingrentprice_monthly' => 1725000,
            'rentprice_yearly' => 13000000,
            'sellingrentprice_yearly' => 14950000,
            'totalbathroom' => 5,
            'extrabed_sellingprice' => 0,
        ]);
        HostelRoom::create([
            'id' => 6,
            'hostel_id' => 4,
            'name' => 'Superior',
            'description' => null,
            'price' => null,
            'sellingprice' => null,
            'bed_type' => null,
            'max_guest' => '2',
            'roomsize' => 11,
            'maxextrabed' => 3,
            'extrabedprice' => 0,
            'totalroom' => 10,
            'roomtype' => null,
            'furnish' => null,
            'is_active' => 1,
            'deleted_at' => null,
            'created_at' => '2023-10-12 18:39:07',
            'updated_at' => '2023-10-12 18:39:07',
            'rentprice_monthly' => 1500000,
            'sellingrentprice_monthly' => 1725000,
            'rentprice_yearly' => 13000000,
            'sellingrentprice_yearly' => 14950000,
            'totalbathroom' => 5,
            'extrabed_sellingprice' => 0,
        ]);
        HostelRoom::create([
            'id' => 7,
            'hostel_id' => 4,
            'name' => 'Deluxe Double',
            'description' => null,
            'price' => null,
            'sellingprice' => null,
            'bed_type' => null,
            'max_guest' => '2',
            'roomsize' => 11,
            'maxextrabed' => 3,
            'extrabedprice' => 0,
            'totalroom' => 8,
            'roomtype' => null,
            'furnish' => null,
            'is_active' => 1,
            'deleted_at' => null,
            'created_at' => '2023-10-12 18:40:17',
            'updated_at' => '2023-10-12 18:40:17',
            'rentprice_monthly' => 1700000,
            'sellingrentprice_monthly' => 1955000,
            'rentprice_yearly' => 15000000,
            'sellingrentprice_yearly' => 17250000,
            'totalbathroom' => 4,
            'extrabed_sellingprice' => 0,
        ]);
        HostelRoom::create([
            'id' => 8,
            'hostel_id' => 4,
            'name' => 'Deluxe Twin',
            'description' => null,
            'price' => null,
            'sellingprice' => null,
            'bed_type' => null,
            'max_guest' => '2',
            'roomsize' => 11,
            'maxextrabed' => 3,
            'extrabedprice' => 0,
            'totalroom' => 15,
            'roomtype' => null,
            'furnish' => null,
            'is_active' => 1,
            'deleted_at' => null,
            'created_at' => '2023-10-12 18:40:25',
            'updated_at' => '2023-10-12 18:40:25',
            'rentprice_monthly' => 1500000,
            'sellingrentprice_monthly' => 1725000,
            'rentprice_yearly' => 13000000,
            'sellingrentprice_yearly' => 14950000,
            'totalbathroom' => 5,
            'extrabed_sellingprice' => 0,
        ]);
    }
}
