<?php

namespace Database\Seeders;

use App\Models\HotelRoom;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class HotelRoomSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        HotelRoom::create([
            'id' => 10,
            'hotel_id' => 3,
            'name' => 'Deluxe Double',
            'description' => null,
            'price' => 175000,
            'sellingprice' => 201250,
            'bed_type' => null,
            'roomsize' => 11,
            'maxextrabed' => null,
            'totalroom' => 11,
            'guest' => 2,
            'is_active' => 1,
            'deleted_at' => null,
            'created_at' => '2023-10-12 18:06:37',
            'updated_at' => '2023-10-12 18:06:37',
            'extrabed_price' => 0,
            'extrabed_sellingprice' => 0,
        ]);
        HotelRoom::create([
            'id' => 11,
            'hotel_id' => 3,
            'name' => 'Deluxe Twin',
            'description' => null,
            'price' => 175000,
            'sellingprice' => 201250,
            'bed_type' => null,
            'roomsize' => 11,
            'maxextrabed' => null,
            'totalroom' => 15,
            'guest' => 2,
            'is_active' => 1,
            'deleted_at' => null,
            'created_at' => '2023-10-12 18:07:28',
            'updated_at' => '2023-10-12 18:07:28',
            'extrabed_price' => 0,
            'extrabed_sellingprice' => 0,
        ]);
        HotelRoom::create([
            'id' => 12,
            'hotel_id' => 3,
            'name' => 'Superior',
            'description' => null,
            'price' => 100000,
            'sellingprice' => 115000,
            'bed_type' => null,
            'roomsize' => 11,
            'maxextrabed' => null,
            'totalroom' => 16,
            'guest' => 2,
            'is_active' => 1,
            'deleted_at' => null,
            'created_at' => '2023-10-12 18:08:27',
            'updated_at' => '2023-10-12 18:08:27',
            'extrabed_price' => 0,
            'extrabed_sellingprice' => 0,
        ]);
        HotelRoom::create([
            'id' => 13,
            'hotel_id' => 4,
            'name' => 'Deluxe Twin',
            'description' => null,
            'price' => 175000,
            'sellingprice' => 201250,
            'bed_type' => null,
            'roomsize' => 11,
            'maxextrabed' => 0,
            'totalroom' => 14,
            'guest' => 2,
            'is_active' => 1,
            'deleted_at' => null,
            'created_at' => '2023-10-12 18:10:18',
            'updated_at' => '2023-10-12 18:10:18',
            'extrabed_price' => 50000,
            'extrabed_sellingprice' => 57500,
        ]);
        HotelRoom::create([
            'id' => 14,
            'hotel_id' => 4,
            'name' => 'Deluxe Double',
            'description' => null,
            'price' => 175000,
            'sellingprice' => 205000,
            'bed_type' => null,
            'roomsize' => 11,
            'maxextrabed' => 0,
            'totalroom' => 11,
            'guest' => 2,
            'is_active' => 1,
            'deleted_at' => null,
            'created_at' => '2023-10-12 18:11:07',
            'updated_at' => '2023-10-12 18:11:07',
            'extrabed_price' => 50000,
            'extrabed_sellingprice' => 57500,
        ]);
        HotelRoom::create([
            'id' => 15,
            'hotel_id' => 4,
            'name' => 'Standard Double',
            'description' => null,
            'price' => 110000,
            'sellingprice' => 126500,
            'bed_type' => null,
            'roomsize' => 11,
            'maxextrabed' => null,
            'totalroom' => 23,
            'guest' => 2,
            'is_active' => 1,
            'deleted_at' => null,
            'created_at' => '2023-10-12 18:12:07',
            'updated_at' => '2023-10-12 18:12:07',
            'extrabed_price' => 0,
            'extrabed_sellingprice' => 0,
        ]);
        HotelRoom::create([
            'id' => 16,
            'hotel_id' => 6,
            'name' => 'Fan Room',
            'description' => null,
            'price' => 150000,
            'sellingprice' => 172500,
            'bed_type' => null,
            'roomsize' => 10,
            'maxextrabed' => null,
            'totalroom' => 10,
            'guest' => 2,
            'is_active' => 1,
            'deleted_at' => null,
            'created_at' => '2023-10-17 19:19:17',
            'updated_at' => '2023-10-17 19:19:17',
            'extrabed_price' => 0,
            'extrabed_sellingprice' => 0,
        ]);
        HotelRoom::create([
            'id' => 17,
            'hotel_id' => 6,
            'name' => 'Superior room',
            'description' => null,
            'price' => 200000,
            'sellingprice' => 230000,
            'bed_type' => null,
            'roomsize' => 10,
            'maxextrabed' => null,
            'totalroom' => 10,
            'guest' => 2,
            'is_active' => 1,
            'deleted_at' => null,
            'created_at' => '2023-10-17 19:28:05',
            'updated_at' => '2023-10-17 19:28:05',
            'extrabed_price' => 0,
            'extrabed_sellingprice' => 0,
        ]);
        HotelRoom::create([
            'id' => 18,
            'hotel_id' => 6,
            'name' => 'Deluxe room',
            'description' => null,
            'price' => 250000,
            'sellingprice' => 287500,
            'bed_type' => null,
            'roomsize' => 10,
            'maxextrabed' => null,
            'totalroom' => 10,
            'guest' => 2,
            'is_active' => 1,
            'deleted_at' => null,
            'created_at' => '2023-10-17 19:36:16',
            'updated_at' => '2023-10-17 19:36:16',
            'extrabed_price' => 0,
            'extrabed_sellingprice' => 0,
        ]);
        HotelRoom::create([
            'id' => 19,
            'hotel_id' => 2,
            'name' => 'Standard',
            'description' => null,
            'price' => 225000,
            'sellingprice' => 258750,
            'bed_type' => null,
            'roomsize' => 11,
            'maxextrabed' => null,
            'totalroom' => 10,
            'guest' => 2,
            'is_active' => 1,
            'deleted_at' => null,
            'created_at' => '2023-10-17 22:30:26',
            'updated_at' => '2023-10-17 22:30:26',
            'extrabed_price' => 0,
            'extrabed_sellingprice' => 0,
        ]);
        HotelRoom::create([
            'id' => 20,
            'hotel_id' => 2,
            'name' => 'Deluxe Double',
            'description' => null,
            'price' => 255000,
            'sellingprice' => 293250,
            'bed_type' => null,
            'roomsize' => 10,
            'maxextrabed' => null,
            'totalroom' => 10,
            'guest' => 2,
            'is_active' => 1,
            'deleted_at' => null,
            'created_at' => '2023-10-17 22:31:46',
            'updated_at' => '2023-10-17 22:31:46',
            'extrabed_price' => 0,
            'extrabed_sellingprice' => 0,
        ]);
        HotelRoom::create([
            'id' => 21,
            'hotel_id' => 2,
            'name' => 'Deluxe Twin',
            'description' => null,
            'price' => 275000,
            'sellingprice' => 316250,
            'bed_type' => null,
            'roomsize' => 10,
            'maxextrabed' => null,
            'totalroom' => 10,
            'guest' => 2,
            'is_active' => 1,
            'deleted_at' => null,
            'created_at' => '2023-10-17 22:32:47',
            'updated_at' => '2023-10-17 22:32:47',
            'extrabed_price' => 0,
            'extrabed_sellingprice' => 0,
        ]);
        HotelRoom::create([
            'id' => 22,
            'hotel_id' => 2,
            'name' => 'Suite',
            'description' => null,
            'price' => 325000,
            'sellingprice' => 373750,
            'bed_type' => null,
            'roomsize' => 10,
            'maxextrabed' => null,
            'totalroom' => 5,
            'guest' => 2,
            'is_active' => 1,
            'deleted_at' => null,
            'created_at' => '2023-10-17 22:33:24',
            'updated_at' => '2023-10-17 22:33:24',
            'extrabed_price' => 0,
            'extrabed_sellingprice' => 0,
        ]);
        HotelRoom::create([
            'id' => 23,
            'hotel_id' => 7,
            'name' => 'VAVAVAVA',
            'description' => null,
            'price' => 325000,
            'sellingprice' => 373750,
            'bed_type' => null,
            'roomsize' => 10,
            'maxextrabed' => null,
            'totalroom' => 5,
            'guest' => 2,
            'is_active' => 1,
            'deleted_at' => null,
            'created_at' => '2023-10-17 22:33:24',
            'updated_at' => '2024-02-11 02:23:48',
            'extrabed_price' => 0,
            'extrabed_sellingprice' => 0,
        ]);
    }
}
