<?php

namespace Database\Seeders;

use App\Models\Transaction;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TransactionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $transactions = [
            [
                'id'=>1,
                'no_inv'=>'INV-20230328-PPOB-1680029051',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/6423357d5967e2d5c0f54dfc',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>NULL,
                'payment_channel'=>NULL,
                'user_id'=>3,
                'status'=>'PENDING',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>2,
                'no_inv'=>'INV-20230329-PPOB-1680130158',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/6424c073efa9027a0e51836f',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>NULL,
                'payment_channel'=>NULL,
                'user_id'=>3,
                'status'=>'PENDING',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>3,
                'no_inv'=>'INV-20230401-PPOB-1680320167',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/6427a6a9f750fdced2d3c347',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>'BANK_TRANSFER',
                'payment_channel'=>NULL,
                'user_id'=>3,
                'status'=>'EXPIRED',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>4,
                'no_inv'=>'INV-20230401-PPOB-1680338793',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/6427ef6b476c3b8d7fdb52c5',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>'BANK_TRANSFER',
                'payment_channel'=>NULL,
                'user_id'=>2,
                'status'=>'PAID',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>5,
                'no_inv'=>'INV-20230401-PPOB-1680368019',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/64286194476c3ba4c4dbaafd',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>'BANK_TRANSFER',
                'payment_channel'=>NULL,
                'user_id'=>2,
                'status'=>'PAID',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>6,
                'no_inv'=>'INV-20230402-PPOB-1680453043',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/6429adb681e688fd4ecc8443',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>'BANK_TRANSFER',
                'payment_channel'=>NULL,
                'user_id'=>2,
                'status'=>'PAID',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>7,
                'no_inv'=>'INV-20230404-PPOB-1680572449',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/642b80231f43660474f36a6d',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>'BANK_TRANSFER',
                'payment_channel'=>NULL,
                'user_id'=>2,
                'status'=>'PAID',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>8,
                'no_inv'=>'INV-20230404-PPOB-1680574418',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/642b87d31f43667ceef374b6',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>'BANK_TRANSFER',
                'payment_channel'=>NULL,
                'user_id'=>2,
                'status'=>'PAID',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>9,
                'no_inv'=>'INV-20230404-HOSTEL-1680634305',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/642c71c37dfc9c6ac96817e4',
                'service'=>'hostel',
                'service_id'=>7,
                'payment'=>'xendit',
                'payment_method'=>NULL,
                'payment_channel'=>NULL,
                'user_id'=>2,
                'status'=>'EXPIRED',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>10,
                'no_inv'=>'INV-20230404-HOSTEL-1680634393',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/642c721be7e27f90b40a0ed9',
                'service'=>'hostel',
                'service_id'=>7,
                'payment'=>'xendit',
                'payment_method'=>NULL,
                'payment_channel'=>NULL,
                'user_id'=>2,
                'status'=>'EXPIRED',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>11,
                'no_inv'=>'INV-20230404-PPOB-1680634430',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/642c723f02f2fc9f66f1c16c',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>'EWALLET',
                'payment_channel'=>NULL,
                'user_id'=>2,
                'status'=>'PAID',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>12,
                'no_inv'=>'INV-20230404-PPOB-1680634881',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/642c740302f2fc5478f1c30a',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>NULL,
                'payment_channel'=>NULL,
                'user_id'=>2,
                'status'=>'EXPIRED',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>13,
                'no_inv'=>'INV-20230404-HOSTEL-1680635030',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/642c7498e7e27f9f7e0a1143',
                'service'=>'hostel',
                'service_id'=>7,
                'payment'=>'xendit',
                'payment_method'=>'BANK_TRANSFER',
                'payment_channel'=>NULL,
                'user_id'=>2,
                'status'=>'PAID',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>14,
                'no_inv'=>'INV-20230404-PPOB-1680642564',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/642c920502f2fca2e0f1d9a9',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>'BANK_TRANSFER',
                'payment_channel'=>NULL,
                'user_id'=>2,
                'status'=>'PAID',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>15,
                'no_inv'=>'INV-20230404-HOSTEL-1680642782',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/642c92e07dfc9cc97f683088',
                'service'=>'hostel',
                'service_id'=>7,
                'payment'=>'xendit',
                'payment_method'=>'BANK_TRANSFER',
                'payment_channel'=>NULL,
                'user_id'=>2,
                'status'=>'PAID',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>16,
                'no_inv'=>'INV-20230406-HOSTEL-1680764063',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/642e6ca2e7e27f0f890bf6d5',
                'service'=>'hostel',
                'service_id'=>7,
                'payment'=>'xendit',
                'payment_method'=>'BANK_TRANSFER',
                'payment_channel'=>NULL,
                'user_id'=>2,
                'status'=>'PAID',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>17,
                'no_inv'=>'INV-20230413-HOSTEL-1681390428',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/6437fb5e5686cfb3ea252475',
                'service'=>'hostel',
                'service_id'=>7,
                'payment'=>'xendit',
                'payment_method'=>NULL,
                'payment_channel'=>NULL,
                'user_id'=>2,
                'status'=>'EXPIRED',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>18,
                'no_inv'=>'INV-20230413-PPOB-1681410146',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/6438486467856e549a66a1bc',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>'BANK_TRANSFER',
                'payment_channel'=>NULL,
                'user_id'=>3,
                'status'=>'PAID',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>19,
                'no_inv'=>'INV-20230413-PPOB-1681413572',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/643855c567856e355c66accf',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>NULL,
                'payment_channel'=>NULL,
                'user_id'=>3,
                'status'=>'EXPIRED',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>20,
                'no_inv'=>'INV-20230420-PPOB-1682005212',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/64415cde5686cfe6282dd86e',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>NULL,
                'payment_channel'=>NULL,
                'user_id'=>3,
                'status'=>'EXPIRED',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>21,
                'no_inv'=>'INV-20230420-PPOB-1682009561',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/64416ddb5686cf90132de5f2',
                'service'=>'pulsa',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>NULL,
                'payment_channel'=>NULL,
                'user_id'=>5,
                'status'=>'EXPIRED',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>22,
                'no_inv'=>'INV-20230420-PPOB-1682014194',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/64417ff75686cf39472df413',
                'service'=>'pulsa',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>'BANK_TRANSFER',
                'payment_channel'=>NULL,
                'user_id'=>5,
                'status'=>'PAID',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>23,
                'no_inv'=>'INV-20230420-PPOB-1682014221',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/6441800f6f99867059c461d0',
                'service'=>'pulsa',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>NULL,
                'payment_channel'=>NULL,
                'user_id'=>5,
                'status'=>'EXPIRED',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>24,
                'no_inv'=>'INV-20230420-PPOB-1682014776',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/6441823a67856e123b6f7975',
                'service'=>'pulsa',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>NULL,
                'payment_channel'=>NULL,
                'user_id'=>5,
                'status'=>'EXPIRED',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>25,
                'no_inv'=>'INV-20230426-PPOB-1682496948',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/6448ddb55686cf96d7347fac',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>NULL,
                'payment_channel'=>NULL,
                'user_id'=>2,
                'status'=>'EXPIRED',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>26,
                'no_inv'=>'INV-20230427-PPOB-1682575485',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/644a10801bf1986d11ea3bd0',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>'BANK_TRANSFER',
                'payment_channel'=>NULL,
                'user_id'=>2,
                'status'=>'PAID',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>27,
                'no_inv'=>'INV-20230510-PPOB-1683685806',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/645b01b0e119c64e283de48e',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>NULL,
                'payment_channel'=>NULL,
                'user_id'=>8,
                'status'=>'EXPIRED',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>28,
                'no_inv'=>'INV-20230510-PPOB-1683700317',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/645b3a5ee119c6a0763e4bd0',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>'BANK_TRANSFER',
                'payment_channel'=>NULL,
                'user_id'=>7,
                'status'=>'PAID',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>29,
                'no_inv'=>'INV-20230511-PPOB-1683764801',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/645c3644e119c6087c3f9a68',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>NULL,
                'payment_channel'=>NULL,
                'user_id'=>8,
                'status'=>'EXPIRED',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>30,
                'no_inv'=>'INV-20230511-PPOB-1683765778',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/645c3a1352b2976c4bb89ccb',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>NULL,
                'payment_channel'=>NULL,
                'user_id'=>8,
                'status'=>'EXPIRED',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>31,
                'no_inv'=>'INV-20230511-PPOB-1683784458',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/645c830b2762c5b7d2c95188',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>NULL,
                'payment_channel'=>NULL,
                'user_id'=>7,
                'status'=>'PENDING',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>32,
                'no_inv'=>'INV-20230511-PPOB-1683784529',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/645c835252b2979189b8fad2',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>'BANK_TRANSFER',
                'payment_channel'=>NULL,
                'user_id'=>7,
                'status'=>'PAID',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>33,
                'no_inv'=>'INV-20230511-PPOB-1683784630',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/645c83b7675a978bb32138b2',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>'BANK_TRANSFER',
                'payment_channel'=>NULL,
                'user_id'=>7,
                'status'=>'PAID',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>34,
                'no_inv'=>'INV-20230511-PPOB-1683785083',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/645c858352b297ce7eb8fd8e',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>'BANK_TRANSFER',
                'payment_channel'=>NULL,
                'user_id'=>7,
                'status'=>'PAID',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>35,
                'no_inv'=>'INV-20230512-PPOB-1683854137',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/645d933d056a2b78535bc3c2',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>NULL,
                'payment_channel'=>NULL,
                'user_id'=>7,
                'status'=>'EXPIRED',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>36,
                'no_inv'=>'INV-20230512-PPOB-1683855692',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/645d994d056a2bc4815bc978',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>NULL,
                'payment_channel'=>NULL,
                'user_id'=>7,
                'status'=>'EXPIRED',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>37,
                'no_inv'=>'INV-20230512-PPOB-1683855926',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/645d9a37056a2b7ddf5bca6f',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>NULL,
                'payment_channel'=>NULL,
                'user_id'=>7,
                'status'=>'EXPIRED',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>38,
                'no_inv'=>'INV-20230512-PPOB-1683856881',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/645d9df21d87fa6d70dd8108',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>'BANK_TRANSFER',
                'payment_channel'=>NULL,
                'user_id'=>7,
                'status'=>'PAID',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>39,
                'no_inv'=>'INV-20230512-PPOB-1683859325',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/645da77e1d87fa078cdd9269',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>NULL,
                'payment_channel'=>NULL,
                'user_id'=>7,
                'status'=>'EXPIRED',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>40,
                'no_inv'=>'INV-20230512-PPOB-1683859355',
                'req_id'=>NULL,
                'link'=>'https://checkout-staging.xendit.co/web/645da79b204c31786c683f44',
                'service'=>'ppob',
                'service_id'=>1,
                'payment'=>'xendit',
                'payment_method'=>'BANK_TRANSFER',
                'payment_channel'=>NULL,
                'user_id'=>7,
                'status'=>'PAID',
                'total'=>0,
                'deleted_at'=>NULL,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        foreach($transactions as $transactionData) {
            Transaction::updateOrCreate(
                ['id' => $transactionData['id']], // Search by ID
                $transactionData // Create or update with this data
            );
        }
    }
}